services:
  social-sync:
    image: ghcr.io/kgonidisorg/social-sync:latest
    container_name: social-sync
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/social_sync
      - DEMO=true
    command: >
      sh -c "sleep 5 &&
         npm run db:push &&
         npm run db:seed &&
         npm run start"
    
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_sync
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata:
    name: pgdata

